// File generated by YOU (manually)
// based on the config files downloaded from Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- ANDROID VALUES ---
  // Find these in: android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfoR4pFs4QIgTIGWJGDzTizEuNIFgd7g',
    appId:
        '1:1041420464929:android:37a2ce0d61911215444460', // From google-services.json: client[0].client_info.mobilesdk_app_id
    messagingSenderId:
        '1041420464929', // From google-services.json: project_info.project_number
    projectId:
        'thingdoms', // From google-services.json: project_info.project_id
    storageBucket:
        'thingdoms.firebasestorage.app', // From google-services.json: project_info.storage_bucket
  );

  // --- IOS VALUES ---
  // Find these in: ios/Runner/GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // From GoogleService-Info.plist: API_KEY
    appId: 'YOUR_IOS_APP_ID', // From GoogleService-Info.plist: GOOGLE_APP_ID
    messagingSenderId:
        'YOUR_MESSAGING_SENDER_ID', // From GoogleService-Info.plist: GCM_SENDER_ID
    projectId: 'YOUR_PROJECT_ID', // From GoogleService-Info.plist: PROJECT_ID
    storageBucket:
        'YOUR_PROJECT_ID.appspot.com', // From GoogleService-Info.plist: STORAGE_BUCKET
    iosClientId:
        'YOUR_IOS_CLIENT_ID', // From GoogleService-Info.plist: CLIENT_ID
    iosBundleId:
        'YOUR_IOS_BUNDLE_ID', // From GoogleService-Info.plist: BUNDLE_ID
  );
}
